version: "3"
services:
  arangodb:
    image: arangodb:latest
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
volumes:
  arangodb_data_container:
  arangodb_apps_data_container: