export enum Sort {
  RATING = 'RATING',
  PRICE_LOW_HIGH = 'PRICE_LOW_HIGH',
  PRICE_HIGH_LOW = 'PRICE_HIGH_LOW',
  MOST_POPULAR = 'MOST_POPULAR',
  MOST_RECENT = 'MOST_RECENT',
  RECOMENDED = 'RECOMENDED',
  SUSTAINABILITY = 'SUSTAINABILITY',
}
